### ISSUE TITLE
No compression for NamedFile?

### ISSUE THREAD

**Issue by dovahcrow** [actix/actix-web#96]
By inspecting the [code](https://github.com/actix/actix-web/blob/master/src/fs.rs#L88), it seems like there's no compression for static files nor named single file. This could lead to large js/css/font/image resources. Is this behavior by design?

**Comment by fafhrd91** [comment]
not really, there was bug in compression (fixed in 0.4.4)

I will re-enable compression for static assets

**Comment by dovahcrow** [comment]
Neat! Hat off for your fast response :P

**Comment by fafhrd91** [comment]
compression enabled in c884442

**Comment by cdaringe** [comment]
hi all,

i'm on 0.5.6 and still not seeing compression.

```rs
fn some_file_handler(req: HttpRequest) -> Result<fs::NamedFile> {
    Ok(fs::NamedFile::open("./my-favorite-file.json")?)
}
```

my request has: `Accept-Encoding: gzip, deflate, br` (chrome default adds it), and the response is as follows:

```
HTTP/1.1 200 OK
content-type: application/json
last-modified: Tue, 24 Apr 2018 01:46:34 GMT
etag: "201391eb2:eecb7:5ade8c7a:e2aac1d"
content-encoding: br
transfer-encoding: chunked
date: Tue, 08 May 2018 03:02:19 GMT
```

as you can see, no compression!  did i miss something?

thanks!

**Comment by cdaringe** [comment]
whoooops. `br` _is_ brotli.  rookie move! nm :)
